.github/workflows/test.yaml, .mypy.ini, .pre-commit-config.yaml, README.md, docs/api.md, docs/conf.py, docs/index.md, pyproject.toml, spatialdata/__init__.py, spatialdata/_core/__init__.py, spatialdata/_core/spatialdata.py, spatialdata/pl/__init__.py, spatialdata/pl/basic.py, spatialdata/pp/__init__.py, spatialdata/pp/basic.py, spatialdata/tl/__init__.py, spatialdata/tl/basic.py, tests/test_basic.py
Initial class and attributes for SpatialData. Also fixed up a fair bit of config + docs.
=> Initial class skeleton

spatialdata/_core/_spatialdata.py, spatialdata/_core/models.py
- Fixes the pyarrow FutureWarning. Closes #87
- Fixes the last line of the repr. Closes #89
=> small fixes

.mypy.ini, .pre-commit-config.yaml, .readthedocs.yaml, docs/api.md, docs/conf.py, pyproject.toml, spatialdata/_constants/_enum.py, spatialdata/_core/_spatialdata.py, spatialdata/_core/coordinate_system.py, spatialdata/_core/core_utils.py, spatialdata/_core/models.py, spatialdata/_core/transformations.py, spatialdata/_io/format.py, spatialdata/_io/write.py, tests/conftest.py
- add hatch as build system
- remove 3.8
- add 3.9
- add `PolygonsModel` to docs (~~from 3.9 they should build~~, they don't but set fail_on_warning=False).
=> deprecate 3.8, add 3.9

docs/_templates/autosummary/class.rst, pyproject.toml
removing and exlcude pattern for doc8 for `class.rst`
=> remove doc8 ignore

spatialdata/_core/_spatialdata.py, spatialdata/_core/models.py
Fixes this issue: https://github.com/scverse/spatialdata/issues/140.
A bit hacky, but for the moment I think we don't have many options.
Sorry for the bad name of the PR, I wanted to fix also another thing but I will limit it to the issue linked.
=> computing len of points directly from parquet

spatialdata/_core/models.py, spatialdata/_core/transformations.py
Use warnings, not logger.warnings.
Basically "libraries warn, applications log", but also really good to be consistent about these things so we can catch them in a consistent way.
=> Use warnings

spatialdata/_io/format.py, tests/conftest.py, tests/test_utils.py
very minor PR from bug report from @melonora
=> fix omero metadata and add test

spatialdata/_core/_spatialdata.py
Fixes https://github.com/scverse/spatialdata/issues/171
=> skip len of points in repr if they are not backed by parquet

src/spatialdata/_core/operations/transform.py, src/spatialdata/transformations/__init__.py, src/spatialdata/transformations/operations.py, tests/test_core/test_operations/test_transform.py
minor fix, I merge directly in main @giovp
=> moved 2 functions in wrong module

docs/contributing.md, src/spatialdata/_core/operations/transform.py, src/spatialdata/_core/spatialdata.py, tests/test_io/test_readwrite.py
fixes to bugs found when running the xenium + visium notebook:
=> transforms fixes

src/spatialdata/_io/io_raster.py
quick fix
closes https://github.com/scverse/spatialdata/issues/201
=> fix for bug with missing channels

src/spatialdata/_core/operations/rasterize.py, src/spatialdata/dataloader/datasets.py
- fix rounding bug in rasterize
- add torch transform argument
=> tiny bugfix

.github/workflows/test_and_deploy.yaml, pyproject.toml
This PR adds a github actions just to deploy to pypi when a tag starting with `v` is pushed to main.
=> add deploy to pypi

pyproject.toml
increase minimum version to include https://github.com/scverse/napari-spatialdata/pull/70
=> bump napari-spatialdata version

docs/index.md
This PR updates the landing page for the docs. In particular
- update note about breaking changes
- link to docs for other packages in the ecosystem
- improve explanation of the library
=> [WIP] update docs landing page

pyproject.toml
pin napari-spatialdata and typing-extensions
=> update dependency pins

docs/api.md, src/spatialdata/__init__.py, src/spatialdata/_core/data_extent.py, src/spatialdata/_core/operations/aggregate.py, src/spatialdata/_core/operations/transform.py, src/spatialdata/_core/query/relational_query.py, src/spatialdata/_core/spatialdata.py, src/spatialdata/_utils.py, src/spatialdata/datasets.py, src/spatialdata/models/_utils.py, src/spatialdata/transformations/_utils.py, src/spatialdata/transformations/transformations.py, tests/conftest.py, tests/core/operations/test_aggregations.py, tests/core/operations/test_spatialdata_operations.py, tests/core/query/test_relational_query.py, tests/core/query/test_spatial_query.py
Removing `id_key` from aggregation to simplify the APIs.
=> Refactoring aggregation

docs/conf.py, docs/index.md, docs/references.bib
Fabian pointed out it wasn't there
cc: @giovp
=> Add preprint reference to docs

tests/core/query/test_relational_query.py
Tiny fix for a test that got broken.
=> fix relational query test

Dockerfile, README.md
Added a simple Dockerfile with the Spatialdata universe packages that that should enable using Spatialdata functions from within the container.
=> Added Docker container

README.md
Reverts scverse/spatialdata#330
Sorry, didn't see that you already had this at the bottom.
=> Revert "Add NumFocus logo and text"

README.md
Added:
~~- [ ] EMBL International PHD Programme~~
~~- [ ] Helmholtz? @giovp~~
~~- [ ] ETH? @kevinyamauchi~~
=> add sponsor attributions

docs/design_doc.md
Mostly minor modifications.
I have added a comment when I deleted larger blocks of text.
=> Updated design doc

.gitmodules, docs/conf.py, docs/index.md
Fix, I had introduced a path changes when working with submodules, but it was not a good idea (the URL got uglier), so I restore.
=> removed submodule notebooks_repo

src/spatialdata/_core/query/relational_query.py
- 1. get_values: improved docstring
- 2. the index of the dataframe returned by `get_values()` now matches the instance_key values for the specified element
Merging straight away because minor PR and because it unlocks other PRs.
=> improved get_values()

src/spatialdata/_core/query/relational_query.py
For labels, get_values() returns a table whose row are sorted by ascending labels value.
=> Sorting labels indices in get_values()

src/spatialdata/_core/data_extent.py, src/spatialdata/models/_utils.py, tests/core/operations/test_transform.py, tests/core/test_data_extent.py
Closes https://github.com/scverse/spatialdata/issues/353
=> Fixes bug with extent of rotated data

docs/design_doc.md, docs/installation.md
Updated installation instructions, also done in napari-spatialdata: https://github.com/scverse/napari-spatialdata/pull/174/files.
=> Update installation.md and roadmap

src/spatialdata/_core/query/relational_query.py, src/spatialdata/_utils.py, src/spatialdata/dataloader/datasets.py, src/spatialdata/models/models.py
Fixed a bug that appeared today/a few days ago, probably due to a new release in pandas. The bug is described here: https://github.com/scverse/anndata/issues/1210
=> Fixed bug with pandas+anndata+categories

src/spatialdata/_core/query/relational_query.py, tests/core/query/test_relational_query.py
Another bug due to https://github.com/scverse/anndata/issues/1210.
=> fixed another bug to catogorical column in obs in anndata views

src/spatialdata/datasets.py
=> removed padding points blobs()

src/spatialdata/_core/spatialdata.py, src/spatialdata/transformations/operations.py, tests/core/operations/test_spatialdata_operations.py
As pointed out in https://github.com/scverse/spatialdata/issues/425#issuecomment-1898505598. Merging right away.
=> locate_element() returns [] instead of None

README.md, docs/design_doc.md, src/spatialdata/_core/operations/transform.py, src/spatialdata/transformations/_utils.py
Tiny PR. I just moved some already existing code into a util function that I need to use in napari-spatialdata to fix https://github.com/scverse/napari-spatialdata/issues/179.
=> added utils scale_radii()

pyproject.toml, src/spatialdata/models/models.py, tests/models/test_models.py
Small PR, the indices of points were reset by the parser.
Closes #470.
=> Fixed and tested index bug points model

src/spatialdata/_core/centroids.py, src/spatialdata/_core/query/spatial_query.py, src/spatialdata/_core/spatialdata.py, src/spatialdata/dataloader/datasets.py, src/spatialdata/transformations/_utils.py, tests/core/operations/test_spatialdata_operations.py, tests/core/test_centroids.py
=> Fixes in get_centroids, spatial_query for multiscale raster, dataloader

src/spatialdata/_core/spatialdata.py
Fixes issue that asking for the instance key column would result in an error because of being ambiguous.
=> fix ambiguous table vector None

src/spatialdata/_core/operations/vectorize.py
=> adjust for geopandas 1.0.0

src/spatialdata/_core/operations/map.py, tests/core/operations/test_map.py
Fix for https://github.com/scverse/spatialdata/issues/597 + added unit test for images -> labels, see https://github.com/ArneDefauw/spatialdata/blob/55f6bea8d73283082abc4f51fedfcc4f328c9545/tests/core/operations/test_map.py#L149
=> map raster c_coords

src/spatialdata/_core/spatialdata.py, src/spatialdata/models/models.py, tests/io/test_multi_table.py
closes #603 
This fixes the issue by adding condition when region is specified as being a series or list.
=> fix setting table region as series or list

src/spatialdata/_core/spatialdata.py, src/spatialdata/models/models.py, tests/io/test_multi_table.py
=> Revert "fix setting table region as series or list"

src/spatialdata/_core/spatialdata.py, tests/io/test_multi_table.py
Had to do refix because changes were pushed unexpectedly from notebooks.
=> redo fix #605

pyproject.toml
Trying relaxing the minimum version of spatial-image, as discussed in Zulip: https://scverse.zulipchat.com/#narrow/stream/443514-spatialdata-dev/topic/new.20prs/near/449067793.
=> spatial-image>=1.0.0

docs/conf.py, src/spatialdata/models/models.py
=> add shapely to intersphinx and use it in docstrings

src/spatialdata/_core/spatialdata.py
Fix a tiny bug introduced with https://github.com/scverse/spatialdata/pull/607/files CC @melonora.
Improves docs.
=> Fix set_table_annotates_spatialelement

README.md
I had trouble finding the installation instructions for M1 Mac, so I updated the link. Thank you for the package!
=> Update installation link and instructions

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, src/spatialdata/_core/query/relational_query.py, src/spatialdata/_core/spatialdata.py, src/spatialdata/_io/io_zarr.py, tests/core/operations/test_aggregations.py, tests/core/operations/test_spatialdata_operations.py
=> Minor fixes: `id()` -> `is`, inplace category subset `AnnData` relational query

CHANGELOG.md, src/spatialdata/_core/_utils.py, src/spatialdata/_core/concatenate.py, tests/core/operations/test_spatialdata_operations.py
=> Improved `concatenate()` for non-unique element names

pyproject.toml
=> (fix): upper bound xarray

src/spatialdata/_core/concatenate.py, tests/core/operations/test_spatialdata_operations.py
Closes #349
The fix is one line of code + 1 test. The rest of the diff is due to pre-commit.
=> Fix bug custom region_key concatenate

src/spatialdata/config.py, src/spatialdata/models/models.py, tests/models/test_models.py
=> Add warning (raster models) when large chunks are detected

.github/ISSUE_TEMPLATE/bug_report.md, README.md, docs/api/io.md, docs/contributing.md, docs/index.md
fixing https://github.com/scverse/spatialdata/issues/889
=> fix docs urls

pyproject.toml
As observed here https://github.com/conda-forge/spatialdata-feedstock/pull/19#issuecomment-2822380058
=> add datashader dependency

src/spatialdata/_io/io_points.py, tests/io/test_remote_mock.py
This PR adds remote filesystem support for points.
=> spatialdata.io.io_points: fix support for remote points

src/spatialdata/_core/spatialdata.py, src/spatialdata/_io/_utils.py, tests/io/test_remote_mock.py
Fixes remote table support and fixes the repr for remote paths
=> spatialdata._io: test remote tables support and fix repr
