scverse/spatialdata

- .gitignore
- README.md
- docs/design_doc.md
This PR adds the initial draft of a design document describing the goals and strategy for designing the SpatialData library.
I propose that we review to make sure this captures our current thoughts as of today, but try and merge quickly (before we change our minds 😉 ). We can continue to revisit and modify as we do the implementation.
> Add initial draft of the design doc

- README.md
As pointed out be @berl in #49 , there are links to docs that point to https://spatialdata.readthedocs.io/en/latest/ on the readme. As those are docs for a different project, this PR removes those links/references.
closes #49
> remove links to readthedocs

- spatialdata/_core/coordinate_system.py
- spatialdata/_core/transformations.py
- tests/_core/test_coordinate_system.py
- tests/_core/test_transformations.py
Added simple repr functions for `BaseTransformation`, `CoordinateSpace`, and `Axis` types.
They're pretty simple, and for the `CoordinateSpace` and `Axis` types can actually be copied and pasted directly into code.
```python
sdata.points["transcripts"].attrs["transform"]
```
```
Scale(input=None, output=CoordinateSystem('xyz', [Axis('x', 'space', 'unit'), Axis('y', 'space', 'unit'), Axis('z', 'space', 'unit')]))
```
I figure these are decent starting point, and a massive improvement over the current reprs.
> Add some simple reprs for transformations, coordinate spaces, and axes

- spatialdata/_core/_spatial_query.py
- spatialdata/_core/_spatialdata.py
- spatialdata/_core/coordinate_system.py
- tests/_core/test_spatial_query.py
This PR adds the infrastructure to perform a bounding box query on a SpatialData object. This implements it for points point to demonstrate the functionality. If we like the API, we can extend to other elements in follow up PRs.
See this comment for an overview: https://github.com/scverse/spatialdata/pull/93#issuecomment-1363292335
> Bounding box query on points

- README.md
- spatialdata/_core/_spatialdata.py
- spatialdata/_core/_spatialdata_ops.py
- spatialdata/_core/_transform_elements.py
- spatialdata/_core/models.py
- spatialdata/_core/transformations.py
- tests/_core/test_spatialdata_operations.py
- tests/_core/test_transformations.py
This PR finishes some work on transformations that was incomplete. In details:
* `print(sdata)` now shows which coordinate systems are available and which elements are in.
* transforming a raster type now prepends the correct translation to the transformed element. This is crucial when the transformation is rotation, so padding is added on the rotated image (for a visualization of this, see last three plots of the [transformations notebook](https://github.com/scverse/spatialdata-notebooks/blob/main/notebooks/transformations_examples.ipynb)).
* added util `_get_affine_for_element()`, which given an element and a transformation, gives an affine transformation with the correct input and output axes.
* added util `_decompose_affine_into_linear_and_translation()`, to split an affine …
> fixed BaseTransformation.transform(); print(sdata) shows coord systems

- spatialdata/_compat.py
- spatialdata/_core/_query_requests.py
- spatialdata/_core/_spatial_query.py
- spatialdata/_core/_spatialdata.py
- spatialdata/_core/_transform_elements.py
- tests/_core/test_spatial_query.py
Hey @LucaMarconato . Here are the transforms added to the bounding box query for points and polygons. This gets the main infrastructure in. We can extend the tests for a few corner cases in a follow up PR.
A couple of notes:
- the queries now return None if no data matches the query. This way the user doesn't have to figure out the specific way to check in an element is empty for each of the different types of elements.
- I had to reset the index on the DaskDataFrame when subsetting the points. Otherwise, the tables get misaligned during the transform because the index doesn't start from 0 and the index of the transformed points that are re-inserted do start from 0. This feels a bit hacky, but I think it's okay for now.
I won't be able to work on this tomorrow, so please feel free to take …
> Add transformations to polygons and points bounding box query

- .editorconfig
- .flake8
- spatialdata/_io/format.py
- spatialdata/_io/read.py
- spatialdata/_io/write.py
- tests/_io/test_format.py
addressed some of the points described in #149 
- split format version per element
- except for images and labels that are grouped together, following ome-zarr format
- removed `@type` and replaced it with `encoding-type`
- added a test for for shapes format
> cleanup format

- .editorconfig
- .flake8
- spatialdata/_core/models.py
- spatialdata/_io/format.py
- spatialdata/_io/read.py
- spatialdata/_io/write.py
- tests/_io/test_format.py
- re-add the categorical conversion as discussed on zulip.
- re-add the `index` argument to `shapes.parse` for matching it with `instance_key` in tables
seems that it still has some commits from the format branch merged shortly before, but are not relevant
linked PR:
- https://github.com/scverse/spatialdata-io/pull/19
- https://github.com/giovp/spatialdata-sandbox/pull/16
> minor fix for points model parser

- pyproject.toml
- spatialdata/_core/_spatialdata.py
- spatialdata/_core/_spatialdata_ops.py
- spatialdata/_core/models.py
- spatialdata/_io/write.py
- tests/_core/test_models.py
- tests/_core/test_spatialdata_operations.py
- tests/conftest.py
as discussed in #158 
changes
things leaving out of this PR as discussed in #158 
-  validation of type of categorical in for instances and instances in labels (should be done in spatialdata)
reason:
- not high priority and postponing to later work to consolidate spatialdata validation (e.g. we need a way to consolidate relationships between elements).
> update table model

- spatialdata/_core/_spatialdata_ops.py
Incorrectly stated that if coordinate_system was None, all transformations are returned.
> Fix docs for get_transformation

- spatialdata/_core/_spatial_query.py
- spatialdata/_core/_spatialdata.py
- spatialdata/_core/_spatialdata_ops.py
- tests/_core/test_models.py
- tests/_core/test_spatial_query.py
- tests/test_utils.py
Small PR closing https://github.com/scverse/spatialdata/issues/167 as asked by @EliHei2:
when performing a bounding box query on a spatialdata object, it is now possible to filter the table to contain only the rows that are annotating any of the elements in the resulting queried object.
> added filter_table param to bounding box query

- .pre-commit-config.yaml
- pyproject.toml
- src/spatialdata/_io/format.py
- src/spatialdata/_io/io_raster.py
- src/spatialdata/models/_utils.py
unfortunately, it looks like omero rewrites the name metadata if present: https://github.com/ome/ome-zarr-py/pull/261
this would require significant rewrite of IO from our side which I wouldn't do now, so using `channel_metadata` for noe.
> revert omero

- README.md
Since we now have the preprint cited on the readme, I am removing the zenodo DOI. Closes #246
> remove zenodo DOI from readme

- docs/index.md
~~for some reason the transparency in dark mode isn't working properly , so I am reverting the banner.~~
it looks like sphinx pydata theme applies a filter: https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/light-dark.html#images-and-content-that-work-in-both-themes
using the `light-dark` class should prevent this.
> fix docs banner background

- src/spatialdata/models/models.py
- tests/core/operations/test_spatialdata_operations.py
Currently it is the case that a user creates a transformation dictionary which is used while parsing multiple data sources into spatialdata elements. When on top of that setting an additional transformation later for one specific element, all the other elements have the transformation set as well. As suggested by @LucaMarconato, this PR fixes this issue by creating a dictionary copy in the parse function if `transformations` is not `None`. Also, a test has been added.
> Tranformation copy

- .gitignore
- src/spatialdata/datasets.py
This is for writing tests in napari-spatialdata where for RGB it is required to specify the number of channels.
> specify n_channels

- src/spatialdata/_core/operations/transform.py
- src/spatialdata/datasets.py
- tests/transformations/test_transformations.py
Closes #295 
- pass c_coords also to newly transformed SpatialImages
- add c_coords to new blobs dataset for debugging
- add tests for blobs dataset with both numerical and string c_coords
Now spatialdata_plot works as expected.
```python
from spatialdata.datasets import blobs
import spatialdata_plot
sdata = blobs(c_coords=['a', 'b'])
sdata.pl.render_images('blobs_image', channel=['a', 'b'], palette=['red', 'blue']).pl.show()
```
> Fix c coords

- src/spatialdata/models/models.py
- tests/models/test_models.py
Fixed bugs and added tests:
* fixed bug (appearing with MERSCOPE data and [described also here](https://github.com/scverse/spatialdata-io/pull/33#issuecomment-1635973682)). In the case in which a dataframe is passed to `PointsModel.parse()` and the dataframe contains both `x` and `another_x`, and `coordinates[`x`] = 'another_x`, then the final parsed dataframe would contain the original column `x` and not `another_x` as expected. Added tests.
* fixed bug where if `coordinates.keys()` are `x` and `y`, but the dataframe contains a `z` column, the `z` column is added to the metadata and the `get_axis_names()` would return `x`, `y`, `z` instead of `x`, `y`. Now the `z` column is not added. Added tests.
* fixed bug same as above, but the parser gets a `np.ndarray` instead. I.e. if the parser …
> fixed bugs in points models

- src/spatialdata/datasets.py
This change is needed for tests in https://github.com/scverse/napari-spatialdata/pull/153 to pass.
(You could seriously consider a monorepository that keeps related code and discussion together, but still release code as separate packages.)
> Fix missing c_coords argument in blobs multiscales

- src/spatialdata/_core/query/spatial_query.py
- tests/core/query/test_spatial_query.py
Small PR, needed for the paper.
> polygon_query() support for images

- src/spatialdata/_core/query/relational_query.py
- tests/core/query/test_relational_query.py
This PR is minor and unlocks other PRs, I'll merge it straight away.
`get_values()` was failing when the internal function `_filter_table_by_elements()` was called with `match_rows=True`, because the aggregated table from blobs doesn't contain the background in the table (for how we implemented the aggregate function), while the labels has it.
To fix, I simply discard the background index when matching a labels element to the table.
Fix an assert that was wrongly written and refactored into the function `_get_element()`
> fix bug with get_values and labels

- .github/workflows/test_and_deploy.yaml
So that things like https://github.com/scverse/anndata/issues/1170#issuecomment-1752057015 are found during the release candidate period
Implementation based off of the scverse cookie cutter: https://github.com/scverse/cookiecutter-scverse/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/test.yaml
> Test against pre-release dependencies

- pyproject.toml
spatialdata pins typing extensions for some reasons that I don't remember, but it often conflicts with other packages in the same env. Would like to merge this asap
> unpin typing extensions

- CHANGELOG.md
- src/spatialdata/_core/query/relational_query.py
`get_values()` is now made more general and it doesn't trigger an error when an element contains instances that are not present in the table and `match_rows` is `True`.
> get_values() and table partially annotating elements

- README.md
- src/spatialdata/transformations/transformations.py
- tests/transformations/test_transformations.py
Helper function for @timtreis as asked in https://github.com/scverse/spatialdata/issues/314.
> decompose affine into simpler transformations

- .pre-commit-config.yaml
- CHANGELOG.md
- src/spatialdata/_core/spatialdata.py
- tests/core/operations/test_spatialdata_operations.py
- tests/core/test_data_extent.py
- `SpatialData.rename_coordinate_systems()`
- No need for review since we want to prioritize bigger PRs
- Tagging you just to make you aware this function exists: @giovp @kevinyamauchi @timtreis @Sonja-Stockhaus @melonora 
Simple but convenient API, I wrote so that I can rename the coordinate systems of Visium samples read with `visium()` before concatenating into a unique object, with one coordinate system per sample.
> Added api for renaming coordinate systems

- .readthedocs.yaml
- README.md
- docs/_templates/autosummary/class.rst
- docs/api.md
- pyproject.toml
- src/spatialdata/__init__.py
- src/spatialdata/_core/concatenate.py
- src/spatialdata/_core/data_extent.py
- src/spatialdata/_core/operations/aggregate.py
- src/spatialdata/_core/operations/rasterize.py
- src/spatialdata/_core/query/relational_query.py
- src/spatialdata/_core/query/spatial_query.py
- src/spatialdata/_core/spatialdata.py
- src/spatialdata/_io/_utils.py
- src/spatialdata/_io/io_zarr.py
- src/spatialdata/_utils.py
- src/spatialdata/dataloader/__init__.py
- src/spatialdata/dataloader/datasets.py
- src/spatialdata/datasets.py
- src/spatialdata/models/_utils.py
- src/spatialdata/models/models.py
- src/spatialdata/transformations/operations.py
- tests/conftest.py
- tests/core/operations/test_aggregations.py
- tests/core/operations/test_spatialdata_operations.py
- tests/core/operations/test_transform.py
- tests/core/query/test_spatial_query.py
- tests/dataloader/test_datasets.py
- tests/io/test_readwrite.py
- tests/models/test_models.py
This PR is a refactoring of the dataloader. It introduces the following improvements:
**Considerations for future work**
While I tried to also make it usable for the labels as regions, I realized early on that for that we might want a drastically different type of pipeline in that case. Specifically, we might not want to iterate over centroids but over chunks.
> refactor data loader

- CHANGELOG.md
- docs/api.md
- src/spatialdata/__init__.py
- src/spatialdata/_core/spatialdata.py
- src/spatialdata/_io/__init__.py
- src/spatialdata/_io/_utils.py
- tests/io/test_readwrite.py
- tests/io/test_utils.py
When I want to create and force-write SpatialData to some location, not caring whether there exist older files, I would intuitively use the `overwrite=True` argument. A use case is when developing/retrying a script that is supposed to be idempotent, repeatable no matter whether it has been run previously.
However, the code assumes from existing files that the SpatialData is backed (although `path` is None) and refuses to overwrite the supposed backing file.
> Allow force-overwriting existing files (non-backing)

- src/spatialdata/_core/spatialdata.py
- src/spatialdata/_utils.py
@giovp I realized that we incremental io PR was not backward compatible. I therefore added some error messages to communicate to the user the new syntax.
> Added error message for removed add_elements functions

- CHANGELOG.md
- src/spatialdata/_core/query/spatial_query.py
- src/spatialdata/_core/spatialdata.py
- tests/core/operations/test_spatialdata_operations.py
- tests/core/query/test_spatial_query.py
I added an API for subsetting a SpatialData object given a list of elements. This function is similar to `pp.get_elements()` from `spatialdata-plot`, with one of the major differences that it doesn't filter by coordinate system like `pp.get_elements()`. 
Also, I have noticed that when various APIs that use the argument `filter_table=True` where returning a `SpatialData` object with a table with `len` 0, instead of `None`. This was confusing because from the `__repr__` of `SpatialData` it seems that there was no table.
I modified the behavior by setting the table to `None`, but maybe we should allow for tables of zero len and modify the `__repr__` to print such tables. WDYT @giovp @melonora?
---
@timtreis @Sonja-Stockhaus ideally we would have only one function upstream (see …
> Added subset API; fix behavior with zero-len table

- CHANGELOG.md
- src/spatialdata/models/models.py
The checks for categorical dtypes in `models.py` had a bug, fixed. Merging right away. CC @giovp
> fix categorical dtype check

- src/spatialdata/datasets.py
- src/spatialdata/models/models.py
- tests/conftest.py
- tests/core/operations/test_spatialdata_operations.py
- tests/models/test_models.py
Pretty much as in the title. It also checks whether for each region the values in the `instance_key` column in `obs` are unique.
> Enforce instance key to be dtype int

- CHANGELOG.md
- docs/api.md
- src/spatialdata/__init__.py
- src/spatialdata/_core/data_extent.py
- src/spatialdata/_core/operations/_utils.py
- src/spatialdata/_core/operations/aggregate.py
- src/spatialdata/_core/operations/rasterize.py
- src/spatialdata/_core/operations/transform.py
- src/spatialdata/_core/query/spatial_query.py
- src/spatialdata/_core/spatialdata.py
- src/spatialdata/transformations/__init__.py
- src/spatialdata/transformations/operations.py
- tests/core/operations/test_spatialdata_operations.py
- tests/core/operations/test_transform.py
- tests/core/test_data_extent.py
- tests/transformations/test_transformations.py
- Added utils function `transform_to_data_extent()`, useful to create a converted with downscaled images, where all the -transformations are applied and where 1 pixel = 1 physical unit.
- Added `maintain_positioning` argument to`SpatialData.transform_to_coordinate_system()` and `SpatialData.transform_element_to_coordinate_system()`.
- Fixed bug: incorrect offset translation vector for raster data when calling the two above functions, `transform()` was not affected)
- Fixed bug: `transform()` on multiscale raster was returning the offset translation for the most low res scale, not scale0
Most importantly:
- `transform()` now requires the argument `to_coordinate_system` instead of `transformation` (unless `maintain_positioning` is `True`); in fact, non-explicit target coordinate systems may …
> Added `transform_to_data_extent()`, improved `transform()`

- CHANGELOG.md
- docs/api.md
- docs/design_doc.md
- src/spatialdata/__init__.py
- src/spatialdata/_core/query/relational_query.py
- src/spatialdata/_core/spatialdata.py
- src/spatialdata/models/models.py
- tests/core/operations/test_aggregations.py
- tests/core/query/test_relational_query.py
Depends on #444 
This PR adds the possibility of SQL like joins for `SpatialElement`(s) and tables. These functions are private but are accessible through one public function and will replace the current `match_table_to_element`. In case a join would result in an empty dataframe or `AnnData` table, `None` is returned for the specific element. A table can be joined to multiple `SpatialElement` at the time. Joins with of table and images and table to table are not supported through the public function.
Currently, labels are only supported for those joins that do not require filtering of the labels, for example, a `left` join. The joins that are currently supported are `left`, `left_exclusive`, `inner`, `right` and `right_exclusive`.
A further refactor and docstrings will be added once …
> Join elements table

- CHANGELOG.md
- src/spatialdata/_core/operations/aggregate.py
- src/spatialdata/_core/spatialdata.py
- tests/core/operations/test_aggregations.py
When performing aggregations currently it is not possible to give a custom table name. Instead a default name `table` is always given. This PR allows users to define the name of the table resulting from the aggregation.
> add possibility for custom table name

- pyproject.toml
- src/spatialdata/_core/operations/aggregate.py
- src/spatialdata/_core/query/relational_query.py
- tests/core/operations/test_aggregations.py
- tests/core/query/test_relational_query.py
The `table_name` in `get_values` and `locate_values` was not allowed to be None, but this can sometimes be a requirement when for example there is no table annotating the element. This can be the case in `spatialdata_plot`. This PR allows for this.
This PR also fixes the issue of failing docs build due to `import error, no module called SpatialData`. In order to replicate the issue I tried the doc build on the denbi machine `using spinx-build source-dir out-dir -P`. The `-P` flag allows for a debugger without ide allowing to manually try the import of `spatialdata`. This gave an error because there was no module called `pytest`. Adding `sphinx-pytest` to the doc dependencies fixed the issue.
> allow table to be None in get_values and _locate_values

- CHANGELOG.md
- docs/api.md
- pyproject.toml
- src/spatialdata/__init__.py
- src/spatialdata/_core/centroids.py
- src/spatialdata/_core/operations/transform.py
- tests/core/test_centroids.py
- tests/core/test_data_extent.py
Function to get the centroids of a points, shapes (circles, polygons, multipolygons), labels element (single/multi scale) in a designed coordinate system.
> `get_centroids()`

- pyproject.toml
Dask DataFrame is now using `dask-expr` as backend; pinning down the version temporarily until we address the changes required to support it (example there is no `.attrs` in the dataframe).
> fix dask dataframe dependency

- src/spatialdata/_core/query/spatial_query.py
- tests/io/test_readwrite.py
Rechunks the raster data (chunks are computed automatically) after a spatial query of raster data.
> rechunking raster data after spatial query

- src/spatialdata/models/models.py
- tests/core/test_data_extent.py
- tests/models/test_models.py
Polygons with a z dimension may not be handled correctly (for instance get_extent fails). Here I add a warning to inform the user of this possibility.
> Warning for Polygon wiht z dimension

- src/spatialdata/dataloader/datasets.py
- src/spatialdata/datasets.py
- tests/dataloader/test_datasets.py
This PR improves the `ImageTilesDataset` class in the following ways.
- General minor cleanup, validation of the arguments and improvement of the docstring.
- Now the regions to derive the tiles from can also be labels and multiscale lables; before only polygons, multipolygons and circles were supported. Points are not supported.
- Now the dataset works also with multiscale images, both if `rasterize` is `True` or `False`. The output is always a single scale image.
- The implementation is now simplified thanks to the use of `to_circles()` API; in particular in `_get_tile_coords()` there is no need anymore to perform affine matrix multiplications manually.
- I removed the logic around `polygon.length`. Before if the regions were polygons or multipolygons, the perimeter of these polygon …
> Fixes on dataloaders

- src/spatialdata/_core/operations/aggregate.py
- src/spatialdata/_core/query/_utils.py
- src/spatialdata/models/models.py
Tiny PR.
- fixes dtype for instance_key allowing it to be `int` and not just `np.int16`, `np.int32`, `np.int64`, `"O"`
- adds `resolution` for the conversion of circles to polygons, especially when used in `aggregate()`
> minor fixes aggregate (.buffer() resolution), model dtype

- CHANGELOG.md
- src/spatialdata/_core/spatialdata.py
- tests/io/test_multi_table.py
Added function for setting the annotation target of a table that is outside a SpatialData object. This function has a slightly different name from its counterpart. This because this is specific to setting the annotation target. 
I did think about a single dispatch method, but in that case the counterpart wouldn't be specific to a spatialdata object.
The function for dealing with tables outside a spatialdata object is useful when performing a SQL like join operation that results in a table changing the annotation targets from 2 to 1 target. I did not allow for directly just specifying regions as anyways we have to do a validation which would require checking the unique elements in the column.
Instance_id is not included as this is typically not changing. If it does change the user should …
> add static set annotation

- CHANGELOG.md
- docs/api.md
- src/spatialdata/__init__.py
- src/spatialdata/_core/query/relational_query.py
- src/spatialdata/dataloader/datasets.py
- tests/core/operations/test_spatialdata_operations.py
- tests/core/operations/test_transform.py
- tests/core/query/test_relational_query.py
- tests/core/query/test_spatial_query.py
- tests/datasets/test_datasets.py
- tests/io/test_readwrite.py
This PR adds a function `join_spatialelement_table` which is equivalent to `join_sdata_spatialelement_table` but does not require the elements to be part of a SpatialData object.
> Join outside sdata

- CHANGELOG.md
- README.md
- src/spatialdata/_core/query/relational_query.py
- tests/core/query/test_relational_query.py
> refactoring join

- src/spatialdata/_core/spatialdata.py
- tests/core/operations/test_spatialdata_operations.py
- tests/io/test_readwrite.py
update unit test incremental io on disk, see https://github.com/scverse/spatialdata/pull/501#issuecomment-2016568527
> update test read write on disk

- .github/workflows/build.yaml
- .github/workflows/test_and_deploy.yaml
Using setup-python v4 with pip caching. It should run noticeably faster, let's see.
We may need to upload a second commit to see the caching mechanism in action.
> Update build.yaml to use setup-python v4

- CHANGELOG.md
- docs/api.md
- src/spatialdata/_io/_utils.py
- src/spatialdata/_io/format.py
- src/spatialdata/models/__init__.py
- src/spatialdata/models/_utils.py
- src/spatialdata/models/models.py
- moved `get_channels()` in `spatialdata.models._utils` from IO utils
- added it in docs
- small doc change around `c_coords`
- updated tutorial notebooks
> fixes on docs, updated notebooks

- CHANGELOG.md
- docs/api.md
- src/spatialdata/models/__init__.py
- src/spatialdata/models/_utils.py
- src/spatialdata/models/models.py
- tests/models/test_models.py
- fixed docstrings data model
- added an implementation of `force_2d()` utils function valid for `GeoDataFrame` constructed with `ShapesModel.parse()`. `force_2d()` is available in `geopandas` but not release yet and it's needed for https://github.com/scverse/napari-spatialdata/issues/218.
> fix models docstrings

- src/spatialdata/transformations/_utils.py
- tests/transformations/test_transformations_utils.py
Useful to facilitate interoperability with tools that only support affine transformations. @keller-mark
> Utils to turn all transformations to affine

- src/spatialdata/_core/spatialdata.py
- src/spatialdata/_utils.py
I have updated the `deprecation_alias` to be flexible enough for implementation across the ecosystems and to handle different arguments with deprecations in different versions.
Example
```
@deprecation_alias(table="tables", version="version 0.1")
def your_function(tables):
do something...
your_function(table)
```
This will now give a message that table is set for deprecation from version 0.1 onwards. The message will also include the library so if a deprecation_alias decorator is applied in a function in spatialdata-plot then it will indicate the spatialdata-plot library in the message.
@timtreis probably useful for the spatialdata-plot refactor.
> updated deprecation_alias

- src/spatialdata/__init__.py
I think it would be nice that this works
```python
import sdata as sd
sdata = sd.datasets.blobs()
```
atm only `from spatialdata.datasets import blobs` works
> add datasets as module

- src/spatialdata/_core/operations/rasterize.py
- src/spatialdata/_core/query/relational_query.py
- tests/conftest.py
- tests/core/query/test_relational_query.py
This PR allows to also pass an `AnnData` table as `element`. If `element_name` is `None` then a whole column is returned but if it is specified than the column is a subset only including those rows annotating the `element_name`. Docstrings have been updated to reflect this.
Furthermore, this PR also allows for getting values from `obsm`.
> support AnnData table with get_values

- CHANGELOG.md
- src/spatialdata/__init__.py
- src/spatialdata/_core/query/relational_query.py
- tests/core/query/test_relational_query.py
This makes the `_get_element_annotators` function public. See also: https://github.com/ckmah/bento-tools/issues/140#issuecomment-2186507825
> make get_element_annotators public

- src/spatialdata/__init__.py
To address an import error if an old dask version is installed.
> Fix check dask-exprs available for old dask versions

- CHANGELOG.md
- src/spatialdata/_core/operations/transform.py
- tests/transformations/test_transformations.py
When transforming a MultiscaleSpatialImage, a KeyError is raised. See https://github.com/scverse/spatialdata/issues/378
So far, I've modified the test case to cover both SpatialImage and MultiscaleSpatialImage and reproduce the problem. I have no proposed fix yet.
> Fix channel names in transform for MultiscaleSpatialImage

- src/spatialdata/_core/spatialdata.py
- src/spatialdata/models/_utils.py
- src/spatialdata/models/models.py
- tests/io/test_multi_table.py
closes #580 
When setting a new annotation target of the table, the region column was not checked to be a categorical so if the user didn't do this it would fail on write. This PR fixes that issue by adding a new function to check whether the column is categorical and converting it. This is used in two places, in the parsing method of the table model and in the function that sets the annotation target.
> Fix #580 region column to categorical

- CHANGELOG.md
- src/spatialdata/_core/spatialdata.py
- tests/core/operations/test_transform.py
closes #604 
Changed the parameter to `element_name` which should be a string. I opted against allowing both elements and element_name as this would require a default of `None` for both which would require a change in argument order.
> Adjust transform_element_to_coordinate_system parameter

- pyproject.toml
Removing the recently incorreclty added `pygeos` dependency (I had incorrectly readded it when trying to fix the conda install).
I will try, in this PR, also to relax the `fsspec` constraint.
> Removed recently added pygeos dep

- pyproject.toml
The current dask dependency constraint can cause issues when using python 3.11 as reported here: https://github.com/dask/dask/issues/11038. This PR updates the dependency to the version in which the fix has been implemented.
> Update dask dependency

- src/spatialdata/models/models.py
Segmentation models can return `uint`. This wasn't supported. This PR adds the `uint` dtypes to be accepted when validating the table annotation metadata.
> allow for uint

- docs/design_doc.md
Updated the design doc (also via this commit https://github.com/scverse/spatialdata/commit/8fb9a2f5618193712fb5220d0252aec670d11697) to add suggestions for the default names for `region_key` and `instance_key`.
> Updated design doc

- CHANGELOG.md
- src/spatialdata/_core/query/spatial_query.py
- src/spatialdata/dataloader/datasets.py
- tests/core/query/test_spatial_query.py
- tests/dataloader/test_datasets.py
I would need this refactor in order to move on with the data loader performance PR. @LucaMarconato what this PR basically does is unifying the building request code for `DataArray|DataTree` with the already existing `_get_bounding_box_corners_in_intrinsic_coordinates` for `DaskDataFrame|GeoPandasDataFrame`. I *think* this is correct, as in the tests for `spatial_query` pass, but I am not sure that the logic is correct.
I had to disable the tests for the dataloaders but they will be worked out in a separate PR. This PR is ready to review, but I would not merge it for now, and wait for finishing the dataloader improvement work.
> refactor bounding box

- src/spatialdata/_core/operations/rasterize_bins.py
- src/spatialdata/_core/query/relational_query.py
- only csr matrices were supported in `get_values()`, fixed
- improved docs for `rasterize_bins()` to show how to plot the rasterized image with `spatialdata-plot`
> small fixes rasterize_bins() and get_values()

- src/spatialdata/_core/operations/rasterize_bins.py
- src/spatialdata/models/models.py
- tests/core/operations/test_rasterize_bins.py
- tests/models/test_models.py
closes #650 
closes #649
More on the linked issues, but in short:
- rasterize bins now work also for polygons and multipolygons
- there was a problem when parsing points whose index was not monotonically increasing
> fix rasterize_bins for polygons; fix points model for unsorted index

- src/spatialdata/models/models.py
- tests/models/test_models.py
Nan or inf values for radii in shapes (circles) were passing validation and potentially leading to bugs downstream, such as one reported for Xenium 2.0.0 data: https://github.com/scverse/spatialdata-io/issues/173.
> Added validation check for inf/nan radius for shapes

- src/spatialdata/models/models.py
- tests/models/test_models.py
I simplified the handling of divisions in the points model when dealing with a non-ascending index and added tests.
> Simplified points model handling of divisions

- src/spatialdata/dataloader/datasets.py
- tests/dataloader/test_datasets.py
The `ImageTilesDataset` class cannot be used if the table you want to work with is not called "table", since there are lines where this name is hard-coded, even though the class allows for a `table_name` to be specified. 
An example where this fails is if you follow this [tutorial](https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/densenet.html) but specify a different table name when creating the dataset. 
This PR replaces instances of "table" with `table_name`.
> Fix dataloader table names

- CHANGELOG.md
- src/spatialdata/_core/query/spatial_query.py
- src/spatialdata/_core/spatialdata.py
- tests/core/query/test_spatial_query.py
Closes https://github.com/scverse/spatialdata/issues/644.
This PR adds `clip: bool = False` as a parameter to `polygon_query`. The behavior is described in the docstring, that I copy here: 
```
clip
If `True`, the shapes are clipped to the polygon. This behavior is implemented only when querying
polygons/multipolygons or circles, and it is ignored for other types of elements (images, labels, points).
Importantly, when clipping is enabled, the circles will be converted to polygons before the clipping. This may
affect downstream operations that rely on the circle radius or on performance, so it is recommended to disable
clipping when querying circles or when querying a `SpatialData` object that contains circles.
```
Importantly also:
- clipping is not enabled for a bounding box query. It …
> Add clip parameter to polygon_query; tests missing

- src/spatialdata/models/models.py
In `spatialdata-io` (e.g. in `xenium()`) we generally want the `sort=True`, here I enable this via a parameter.
> Add sort parameter to points model

- docs/api.md
- src/spatialdata/datasets.py
Improved docs explaining how to use the example datasets `blobs`, `raccoon` and how to use `blobs_annotating_element`.
> Docs for datasets (blobs, raccoon)

- src/spatialdata/models/models.py
- tests/models/test_models.py
Closes #696 
When passing `scale_factors` to a RasterSchema, and it is for labels instead of images, the default for `to_multiscale`'s `method` argument was `xarray_coarsen` and caused artifacts on labels edges. It is now overriden to `dask_image_nearest`. This avoids artifacts if the user does not explicitly pass a method.
Questions:
- Is there any other scaling method to consider, or can `dask_image_nearest` handle all array types?
- Pydocstyle complains about missing docstring. It is a static analyzer and cannot detect inheritance of docstrings. I didn't want to copy the complete docstring and cause duplication. Currently, I disabled the check. How do you prefer to handle this?
> Fix labels multiscales method

- src/spatialdata/_core/query/_utils.py
- src/spatialdata/_core/query/spatial_query.py
- src/spatialdata/_docs.py
- tests/core/query/test_spatial_query.py
Trying to vectorize the tiling in the dataloader PR, realized some improvements should be added separately.
With this PR, I enable the vectorization of `bounding_box_query`  for all elements. 
This means that it is now possible to pass an array of bounding boxes (and not just one). 
TODO:
@LucaMarconato @melonora do you have any suggestion of when this could be used to replace current implementations across the projects? A clear use case (and the motivation for this contribution) is the dataloader, see #687 for the speedup, but I wonder if there are other places where this is useful. 
This also is the groundwork for eventual update to the dataloader, being able to return batches of all elements.
considering that this PR is already getting too large, I would postpone the vectorization of …
> vectorize bounding box query

- CHANGELOG.md
- src/spatialdata/transformations/operations.py
- tests/core/operations/test_transform.py
Related to issue #713, CC @LucaMarconato
Note that I changed the structure of the code, which was highly nested. The logic should be the same though
I also added some tests!
> Added `shortest_path` parameter to `get_transformation_between_coordinate_systems`

- src/spatialdata/models/models.py
Better docs, especially around rgba and c_coords.
This PR replaces https://github.com/scverse/spatialdata/pull/702/files.
> Better docstring raster model

- CHANGELOG.md
- docs/api.md
- src/spatialdata/__init__.py
- src/spatialdata/_io/_utils.py
- src/spatialdata/_io/io_raster.py
- src/spatialdata/_utils.py
- src/spatialdata/models/models.py
- tests/core/operations/test_rasterize.py
Small PR adding the `spatialdata.get_pyramid_levels()` util function.
closes #106 (was mostly implemented already)
closes #355
> Fix validation and scale accessor multiscale image

- CHANGELOG.md
- pyproject.toml
- src/spatialdata/_io/io_raster.py
- tests/io/test_pyramids_performance.py
Closes #577 
- When doing multiple computations in Dask, it is better to submit them at once so that Dask can optimize the computational graph, re-use intermediate results and avoid recomputations.
- This capability was added to ome-zarr-py in [#257](https://github.com/ome/ome-zarr-py/pull/257) as a flag `compute=True` that can optionally be disabled to control the computation on your own. However, SpatialData kept the default enabled.
- As a consequence, every pyramid level was computed separately, and had to read again the whole input image from disk (if disk-backed). Due to this, the performance decreased with the number of scale factors:
$$n := \textrm{number of pixels of scale level 0}$$
$$f := \textrm{number of scale factors}$$
$$\mathcal{O}\biggl(n \cdot (f+1)\biggr)$$
By disabling …
> Improve performance of writing pyramids

- pyproject.toml
The integration CI is failing with spatialdata most likely because torch is not a test dependency (because of the github workflow only installing like this `pip install -e .[test]` the torch dependency is missing when running the dataloader tests.
Here torch is now included in test and the github workflow is adjusted to reflect that.
> fix integration CI

- pyproject.toml
- src/spatialdata/datasets.py
Closes #602 
Also adds `numba` to the dependencies as asked by @ilan-gold.
> Fix numpy 2.0 support; add numba to deps

- pyproject.toml
Due to new release of `multiscale-spatial-image` it can lead to problems as it uses the version of xarray that already directly imports datatree.
> hotfix multiscale spatial image

- .pre-commit-config.yaml
- CHANGELOG.md
Some of the default stage names have been deprecated for `pre-commit`. This PR introduces the update as suggested by pre-commit to migrate the config: `pre-commit migrate-config`.
> migrated pre-commit config

- src/spatialdata/_core/query/_utils.py
One-character PR to remove the following warning during the import of spatialdata:
```
RuntimeWarning: nopython is set for njit and is ignored
```
Very minor PR, not urgent.
See [here](https://github.com/numba/numba/blob/0f363d1b2dd19f2aa1a8cec5f0a99c3dd95512f8/numba/core/decorators.py#L239) the difference between `numba.jit` and `numba.njit`.
> I was annoyed about this warning when running segmentation: for instance, with 50 workers, the warning gets duplicated 50 times and breaks the progress bar.
> Use numba jit instead of njit to remove warning

- src/spatialdata/datasets.py
- src/spatialdata/models/models.py
- tests/models/test_models.py
This PR implements one of the tasks in #750 to improve the handling of channel names. It moves the `c_coords` parameter out of kwargs and also adds a validation for a mismatch in length between `c_coords` and the length of the `c` dimension.
> Move c_coords out of kwargs

- pyproject.toml
The newest release of multiscale-spatial-image now includes methods such as `transpose` and `reindex` that are used in other spatialdata libraries. For this the dependency here must be updated.
> update multiscale-spatial-image dependency

- CHANGELOG.md
- pyproject.toml
- src/spatialdata/_core/query/spatial_query.py
- src/spatialdata/models/_utils.py
- src/spatialdata/models/models.py
- tests/core/query/test_spatial_query.py
In bounding_box/polygon queries, the `"feature_key"` of points was not preserved.
While fixing that, I also found (and fixed) a minor issue in the `PointsModel.parse` method when passing `feature_key`. Indeed, if corresponding column is already a category, it is dropped from the dataframe, see the line below:
```python
if feature_key is not None and data[feature_key].dtype.name != "category":
table[feature_key] = data[feature_key].astype(str).astype("category")
```
> Preserve points feature_key in queries

- pyproject.toml
Before the installation was not working due to this bug: https://github.com/ome/ome-zarr-py/issues/302.
> relaxed fsspec version

- CHANGELOG.md
- src/spatialdata/_core/_deepcopy.py
- src/spatialdata/_core/concatenate.py
- src/spatialdata/_core/operations/_utils.py
- src/spatialdata/_core/operations/rasterize.py
- src/spatialdata/_core/operations/transform.py
- src/spatialdata/_core/query/spatial_query.py
- src/spatialdata/_core/spatialdata.py
- src/spatialdata/_io/format.py
- src/spatialdata/_io/io_zarr.py
- tests/core/operations/test_rasterize.py
- tests/core/operations/test_spatialdata_operations.py
- tests/core/test_deepcopy.py
- tests/io/test_readwrite.py
As described in issue #404, it is useful to have attributes at the `SpatialData` object level. This will also be useful in Sopa, to simplify the API.
```python
import spatialdata
from spatialdata.datasets import blobs
sdata = blobs()
sdata.attrs # empty dictionnary
sdata.attrs["test"] = 12
sdata.write("blobs.zarr") # this saves the attributes on disk
sdata = spatialdata.read_zarr("blobs.zarr") # the attributes are read normally
sdata.attrs["test"] # returns 12
```
What do you think @LucaMarconato?
> Adding `attrs` at the `SpatialData` object level

- src/spatialdata/_core/operations/vectorize.py
I noticed that when configuring dask to use 'processes' instead of 'threads' , `spatialdata.to_polygons` fails due to this line:
https://github.com/scverse/spatialdata/blob/27bb4a7579d8ff7cc8f6dd9b782226cb984ceb20/src/spatialdata/_core/operations/vectorize.py#L212
result of `dask.compute() `is lost when using processes, which is expected behaviour.
Note that using 'processes' instead of 'threads' considerably speeds up vectorizing labels for large masks, because the function we try to parallelize does not release the GIL.
Example:
```
import os
from pathlib import Path
import pooch
from pooch import Pooch
from spatialdata import read_zarr
BASE_URL = "https://objectstor.vib.be/spatial-hackathon-public/sparrow/public_datasets"
def _get_registry(path: str | Path | None = None) -> Pooch: …
```
> fix for to_polygons when using processes instead of threads in dask

- .github/ISSUE_TEMPLATE/bug_report.md
- CHANGELOG.md
- README.md
- src/spatialdata/_core/_elements.py
- src/spatialdata/_core/spatialdata.py
Fix of incorrect arguments and typehints when setting tables. Also each table was not validated when setting `tables` within `SpatialData`. Lastly, `sdata.tables.keys()` would return an incorrect `KeysView` as both keys and values would be returned within the `KeysView`. This has been corrected. Idem for `ValuesView`.
> validate tables while parsing

- src/spatialdata/_core/operations/_utils.py
- tests/core/operations/test_spatialdata_operations.py
This PR ensures `transform_to_data_extent` preserves the data type of labels and does not convert them to images. Here, I chose the most minimal solution to pass the (missing) parameter `return_regions_as_labels=True` and override its default of `False`.
Meanwhile, @quentinblampey has already documented the parameter `return_regions_as_labels` in `rasterize`.
Closes #783
> Fix `transform_to_data_extent` converting labels to images

- src/spatialdata/_core/query/relational_query.py
- tests/core/query/test_relational_query.py
Currently, matching an element to non matching table (sliced table) can fail when `match_rows` is not `no`. 
For example on main this would fail:
```
from spatialdata.datasets import blobs_annotating_element
from spatialdata import join_spatialelement_
sdata = blobs_annotating_element("blobs_circles")
sdata['table'] = sdata['table'][:3]
el, table = join_spatialelement_table(sdata, spatial_element_names="blobs_circles", table_name="table", how="inner", match_rows="left")
```
This PR fixes that issue.
> fix join non matching table

- src/spatialdata/_core/query/relational_query.py
- tests/core/query/test_relational_query.py
Closes #815 
The current way the join works on main does not account for duplicate indices in `table.obs.index`. This leads to a problem when performing the join as the indices are used to subset the table. 
The implemented fix here gets the indices of the masked elements and then does a boolean masking on the obs dataframe with the index reset. This retrieves the integer indices which can then be used for subsetting the table. The behaviour of matching rows stays unchanged with this change.
```
from pathlib import Path
import spatialdata as sd
import spatialdata_plot
visium_zarr_path = Path("C:/Users/w-mv/PycharmProjects/spatialdata-notebooks/notebooks/examples/visium_brain.zarr")
visium_sdata = sd.read_zarr(visium_zarr_path)
(
visium_sdata.pl.render_images(elements="ST8059050_hires_image …
```
> Join with duplicate obs indices

- src/spatialdata/_core/query/relational_query.py
closes #829 
There was a problem when a mutable copy was created when performing an `inner join`. This was due to slicing using an `Index` which did not have the method `.reshape`. This is fixed in this PR by converting it to a list.
Tested on the squidpy notebook.
> fix index cannot be reshaped with inner join

- src/spatialdata/_core/query/relational_query.py
follow up from #832 due to unpushed commit fixing the same problem for left join.
> fix index error left join

- .github/workflows/build_image.yml
- Dockerfile
- docs/installation.md
This PR:
- improves the `Dockerfile`
- Replaces the approach drafted here https://github.com/scverse/spatialdata/pull/326
- introduces a workflow for automatically building a Docker daily, as follows:
- the container includes the latest available versions of `spatialdata` (with `torch`), `spatialdata-io`, `spatialdata-plot`. Not `napari-spatialdata`
- to trigger the build of the container you need to manually run the GitHub action. If things work as expected (let's test it for a few releases), we can uncomment the part that runs the workflow everyday
- the docker container will contain all the 3 spatialdata-xx versions in the tag, and available here: https://github.com/scverse/spatialdata/pkgs/container/spatialdata/versions
- running the workflow everyday will ensure that the docker …
> Docker automatic build

- .pre-commit-config.yaml
- benchmarks/spatialdata_benchmark.py
- benchmarks/utils.py
- docs/extensions/typed_returns.py
- pyproject.toml
- src/spatialdata/_core/operations/aggregate.py
- src/spatialdata/_core/operations/rasterize.py
- src/spatialdata/_core/operations/transform.py
- src/spatialdata/_core/operations/vectorize.py
- src/spatialdata/_core/query/relational_query.py
- src/spatialdata/_core/spatialdata.py
- src/spatialdata/_io/_utils.py
- src/spatialdata/dataloader/datasets.py
- src/spatialdata/testing.py
- src/spatialdata/transformations/operations.py
- tests/conftest.py
- tests/core/operations/test_rasterize_bins.py
- tests/core/query/test_spatial_query.py
- tests/io/test_metadata.py
- tests/io/test_multi_table.py
- tests/models/test_models.py
- tests/transformations/test_transformations.py
We are already using Ruff for linting so might as well use it's lightning fast code formatting instead of Black. The implementations and resulting formatting are very close but there can be tiny changes.
> Use Ruff for code formatting

- .github/workflows/test.yaml
- src/spatialdata/_core/query/relational_query.py
Hotfix for https://github.com/scverse/spatialdata/issues/852
> Fix JoinTypes.__dict__ empty python 3.13

- .github/workflows/test.yaml
- pyproject.toml
This reverts commit 1f8a01cf97dee96a3fa957234b2f5e8a0732d7e0. (i.e. removes Python 3.13 support). The latest release doesn't support 3.13, so this will not impact users.
> Revert "Update pyproject.toml"

- pyproject.toml
- src/spatialdata/_core/query/_utils.py
- tests/io/test_pyramids_performance.py
Closes https://github.com/scverse/spatialdata/issues/821 until the root of the problem (https://github.com/dask/dask/issues/11713) is addressed, and until we can update to the latest dask (https://github.com/dask/dask/issues/11146).
> Fix rechunk bug after spatial query

- src/spatialdata/_core/query/relational_query.py
- tests/core/query/test_relational_query.py
This PR is very small (I modified only `src/spatialdata/_core/query/relational_query.py`, the rest is from the new ruff pre-commit).
This PR fixes a subtle bug that originated when all the following occurred simultaneously:
1) we did join operation between an element, and a table that is not annotating the element
2) instead the table is annotating 1 (not 2 or more) other elements
3) the name of the element being annotated is a string that contains the name of the element we are joining against
This occurred for instance with this code:
```python
from spatialdata_io import visium_hd
from pathlib import Path
from napari_spatialdata import Interactive
path = Path("../../spatialdata-sandbox/visium_hd_3.1.1_io")
assert path.exists()
path_read = path / "data"
path_write = path / "data.zarr" …
```
> Fix bug join operation with non-annotating table

- README.md
- docs/installation.md
We cannot offer `spatialdata` in `conda` atm. Details here: https://github.com/conda-forge/spatialdata-feedstock/pull/14. I therefore explain this in the docs and readme.
> Update README.md: conda not available

- .github/workflows/test.yaml
- src/spatialdata/_core/concatenate.py
- tests/core/operations/test_spatialdata_operations.py
Closes #414
Bug reported by @AmosFong1 (thanks!)
> fix suffix concatenate when each table annotates > 1 elements

- src/spatialdata/config.py
- src/spatialdata/models/models.py
- tests/models/test_models.py
Small fix after https://github.com/scverse/spatialdata/pull/874
Also added instructions on how to silence the warning on large chunks.
> fix max chunk size calculation

- .pre-commit-config.yaml
- src/spatialdata/__init__.py
- src/spatialdata/_io/format.py
- tests/io/test_format.py
This PR monkeypatches `ome_zarr.format` to make it possible to use the read/write APIs of `ome-zarr-py`, while clarifying which OME-Zarr data version we are building on top.
Precisely, we implement the [NGFF transformations specification](https://github.com/ome/ngff/pull/138), which, as of today, it is not merged to NGFF main yet. The timeline is to have the specification included in NGFF v0.6, hence from this PR we will write `0.6-dev` instead of `0.4` (which was kept for compatibility with `ome-zarr-py`).
All the tests pass, the code for reproducing the documentation and paper notebooks and the data conversions from `spatialdata-sandbox` are currently running.
Practically, the PR will not change APIs or usage of the function of the `spatialdata` package and will only modify, on-disk, …
> Specify NGFF 0.6-dev in output data

- pyproject.toml
installing with `uv pip` I got errors if I didn't explicitly pin numba
> pin numba to earlierst version supporting python 3.10

- src/spatialdata/_core/operations/aggregate.py
- tests/conftest.py
Fixes https://github.com/scverse/spatialdata/issues/895
No more
```
site-packages/anndata/_core/anndata.py:401: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
```
> Resolve AnnData FutureWarnings `The dtype argument is deprecated`

- src/spatialdata/_core/_elements.py
- src/spatialdata/_core/spatialdata.py
- src/spatialdata/testing.py
Currently, when we get an item by name, e.g. `geo_df = sdata.shapes["boundaries"]`, then the type of `geo_df` is not inferred and we lose type hints and auto-completion.
This PR aims to fix this, via the use of `TypeVar`, to precise the type of each element.
I also added `AnnData` to the return types of `SpatialData.__getitem__`
> Add type hint when get a SpatialElement item

- src/spatialdata/_io/io_shapes.py
- tests/io/test_remote_mock.py
This PR adds remote filesystem support for shapes.
> spatialdata.io.io_shapes: fix support for remote shapes
